services:
  cmd:
    build: .
    volumes:
      - .:/app
      - ${RCLONE_CONFIG_PATH}:/root/.config/rclone/:rw
      - ${ARCHIVE_PATH}:/archives/
    working_dir: /app
    environment:
      - "ARCHIVE_PATH=/archives/"
    entrypoint: "tail -f /dev/null"
